1. Określenie słownika słów kluczowych (unia wszystkich słów występujących we wszystkich tekstach)

In [1]:
import os
import re
import collections
import numpy as np

In [2]:
allFiles = next(os.walk('.'))[2]
allFiles = list(filter(lambda x: re.search('.txt', x), allFiles))
allFiles

['central_processor_unit.txt',
 'digital_signal_processor.txt',
 'floating_point_unit.txt',
 'microprocessor.txt']

In [3]:
texts = []
for text in allFiles:
    with open(text, 'r') as myfile:
        data=myfile.read().replace('\n', '')
    texts.append(data)
   

In [4]:
bagsofwords0 = [collections.Counter(re.findall(r'\w+', txt)) for txt in texts]
bagsofwords = sum(bagsofwords0, collections.Counter())
bagsofwords

Counter({'A': 5,
         'central': 5,
         'processing': 9,
         'unit': 12,
         'CPU': 6,
         'is': 8,
         'the': 26,
         'electronic': 1,
         'circuitry': 2,
         'within': 2,
         'a': 33,
         'computer': 8,
         'that': 12,
         'carries': 1,
         'out': 3,
         'instructions': 5,
         'of': 23,
         'program': 2,
         'by': 4,
         'performing': 1,
         'basic': 1,
         'arithmetic': 3,
         'logic': 5,
         'controlling': 1,
         'and': 17,
         'input': 2,
         'output': 2,
         'I': 2,
         'O': 2,
         'operations': 7,
         'specified': 1,
         'The': 5,
         'industry': 1,
         'has': 1,
         'used': 2,
         'term': 2,
         'at': 4,
         'least': 2,
         'since': 2,
         'early': 1,
         '1960s': 1,
         '1': 4,
         'Traditionally': 1,
         'refers': 1,
         'to': 11,
         'processor': 5,
     

2. Wyznaczenie wektora cech bag-of-words dla każdego dokumentu. Zbudowanie rzadkiej macierzy wektorów bag-of-words, w której częstości cech ułożone są kolumnowo.
    

In [37]:
bagsofwordsZeros = bagsofwords.copy()
for x in bagsofwordsZeros:
    bagsofwordsZeros[x] = 0
bagsofwordsZeros

Counter({'A': 0,
         'central': 0,
         'processing': 0,
         'unit': 0,
         'CPU': 0,
         'is': 0,
         'the': 0,
         'electronic': 0,
         'circuitry': 0,
         'within': 0,
         'a': 0,
         'computer': 0,
         'that': 0,
         'carries': 0,
         'out': 0,
         'instructions': 0,
         'of': 0,
         'program': 0,
         'by': 0,
         'performing': 0,
         'basic': 0,
         'arithmetic': 0,
         'logic': 0,
         'controlling': 0,
         'and': 0,
         'input': 0,
         'output': 0,
         'I': 0,
         'O': 0,
         'operations': 0,
         'specified': 0,
         'The': 0,
         'industry': 0,
         'has': 0,
         'used': 0,
         'term': 0,
         'at': 0,
         'least': 0,
         'since': 0,
         'early': 0,
         '1960s': 0,
         '1': 0,
         'Traditionally': 0,
         'refers': 0,
         'to': 0,
         'processor': 0,
         'mo

In [38]:
length = len(bagsofwords.values())
size = len(allFiles)
wordsMatrix = np.zeros((length, size))
words = set(bagsofwords.elements())
i = 0
j = 0

for text in allFiles:
    with open(text, 'r') as myfile:
        data=myfile.read().replace('\n', '')
        
    bagsofwordsVectorCollection = [collections.Counter(re.findall(r'\w+', data))]
    bagsofwordsVector = sum(bagsofwordsVectorCollection, collections.Counter())
    bagsofwordsZerosTmp = bagsofwordsZeros.copy()
    
    for word in set(bagsofwords):
        bagsofwordsVector[word] = bagsofwordsVector[word]
        wordsMatrix[i][j] = bagsofwordsVector[word]
        i+=1
    
    j+=1
    i=0

In [39]:
wordsMatrix

array([[0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       ...,
       [7., 0., 3., 2.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.]])

3. Redukcja znaczenia często występujących słów poprzez pomnożenie otrzymanego zbioru danych przez inverse document frequency.

In [29]:
idfVector = np.zeros(length)

In [48]:
i=0
for word in set(bagsofwords):
    idfVector[i] = np.log(size/bagsofwords[word])
    i+=1
idfVector

array([ 1.38629436,  1.38629436,  1.38629436,  1.38629436,  1.38629436,
        0.69314718,  1.38629436,  1.38629436,  1.38629436,  1.38629436,
       -0.22314355,  1.38629436, -1.09861229,  1.38629436,  1.38629436,
       -0.81093022,  1.38629436,  1.38629436,  1.38629436,  1.38629436,
        1.38629436,  1.38629436,  0.69314718,  1.38629436,  1.38629436,
        0.69314718,  1.38629436, -1.01160091,  1.38629436, -0.22314355,
        1.38629436,  1.38629436,  1.38629436, -0.69314718,  1.38629436,
        1.38629436,  1.38629436,  1.38629436,  1.38629436,  0.        ,
        1.38629436,  0.28768207,  1.38629436,  1.38629436,  1.38629436,
        0.69314718,  1.38629436,  1.38629436,  1.38629436,  0.69314718,
       -1.01160091,  1.38629436,  1.38629436,  1.38629436,  1.38629436,
        1.38629436,  1.38629436,  1.38629436,  0.28768207,  1.38629436,
        0.28768207,  1.38629436,  1.38629436,  1.38629436,  1.38629436,
        1.38629436,  1.38629436,  0.69314718,  1.38629436,  1.38

In [49]:
i=0
j=0
for i in range(0, length):
    for j in range(0, size):
        wordsMatrix[i][j] = wordsMatrix[i][j]*idfVector[i]

In [50]:
wordsMatrix

array([[ 0.        ,  0.        ,  1.38629436,  0.        ],
       [ 0.        ,  1.38629436,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.38629436],
       ...,
       [-7.69028602, -0.        , -3.29583687, -2.19722458],
       [ 1.38629436,  0.        ,  0.        ,  0.        ],
       [ 1.38629436,  0.        ,  0.        ,  0.        ]])

4. Program pozwalający na wprowadzenie zapytania.

In [51]:
query=["multiple", "parallel", "computer"]
k=2 #number of documents to return

In [ ]:
def find(query, k):
    